export enum Type{
    MANGA = "Manga",
    MANHWA = "Manhwa",
    MANHUA = "Manhua",
    NOVELA = "Novela",
    ONE_SHOT = "One Shot",
    DOUJINSHI = "Doujinshi",
    OEL = "Oel"
}

export enum Genders{
    Accion = 1,
    Aventura,
    Comedia,
    Drama,
    Recuentos_De_La_Vida,
    Ecchi,
    Fantasia,
    Magia,
    Sobre_Natural,
    Horror,
    Misterio,
    Psicologico,
    Romance,
    Ciencia_Ficcion,
    Thriller,
    Deporte,
    Girls_Love,
    Boys_Love,
    Harem,
    Mecha,
    Supervivencia,
    Reencarnacion,
    Gore,
    Apocaliptico,
    Tragedia,
    Vida_Escolar,
    Historia,
    Militar,
    Policiaco,
    Crimen,
    Superpoderes,
    Vampiros,
    Artes_Marciales,
    Samurai,
    Genero_Bender,
    Realidad_Virtual,
    Ciberpunk,
    Musica,
    Parodia,
    Animacion,
    Demonios,
    Familia,
    Extranjero,
    Child,
    Realidad,
    Telenovela,
    Guerra,
    Oeste,
    Traps,
}